### ISSUE TITLE
Installing from source leaves .so files in root directory

### ISSUE THREAD

**Issue by alxshine** [martinbenes1996/jpeglib#14]
When installing the package from source with `pip install -e .` (in a venv), the generated .so files for the different libjpeg versions end up in the root directory instead of `libjpeg/cjpeglib`.

This occurs on different machines:
- my work laptop with Fedora 37 and Python 3.11.4
- a testing server (you know which one) running Ubuntu 20.04 and python 3.8.10

Moving the files manually fixes the issue on both machines

**Comment by martinbenes1996** [comment]
Hey, thanks for the spot, I'll take look into it.

Until then, for local installation you can use

```python
python setup.py sdist
python setup.py install
```

**Comment by martinbenes1996** [comment]
Now, `dev` contains the fix. In connection to this issue, I modified the package structure to clean up the root directory a bit.

The fix will be contained in the next release.
