### ISSUE TITLE
install_test_dependencies reruns pip install

### ISSUE THREAD

**Issue by alxshine** [martinbenes1996/jpeglib#15]
the only thing that the `install_dependencies` action does is upgrade pip and install the requirements.txt

The first line in install_test_dependencies repeats this process. Is this on purpose/required?

**Comment by martinbenes1996** [comment]
Thank you for the spot ;) they are two different files, `requirements.txt` and `tests/requirements.txt`. The first one is for the package itself, and the second extends the first one and is used for running unittests.
