### ISSUE TITLE
Integer QF in jpeglib.from_dct

### ISSUE THREAD

**Issue by btlorch** [martinbenes1996/jpeglib#19]
According to the docstring, `jpeglib.from_dct` assumes the quantization table to be either None or to be an ndarray. [The example from the documentation](https://github.com/martinbenes1996/jpeglib/blob/65cf516b30b6db9d065377e0b4d3dfaa33b1b888/src/jpeglib/functional.py#L348) suggests that integer quality factors are also possible, but the example leads to an error.

```python
Y = np.random.randint(-127, 127,(2,2,8,8),dtype=np.int16)
Cb = np.random.randint(-127, 127,(1,1,8,8),dtype=np.int16)
Cr = np.random.randint(-127, 127,(1,1,8,8),dtype=np.int16)
im = jpeglib.from_dct(Y, Cb, Cr, qt=75) # chrominance -> YCbCr infered
```

When only the luminance channel is given, then the jpeglib object is created successfully, but writing to a file fails.

```python
Y = np.random.randint(-127, 127, (2, 2, 8, 8), dtype=np.int16)
im = jpeglib.from_dct(Y, qt=75)
im.write_dct("/tmp/tmp.jpg")
```

A simple solution would be to disallow integer quality factors. Another solution would be to retrieve the quantization tables for the given quality factor.

**Comment by martinbenes1996** [comment]
Thank you for the bug report. Will take a look at it next week.

**Comment by martinbenes1996** [comment]
Amazing spot! The fix commit https://github.com/martinbenes1996/jpeglib/commit/5bf7d013b8eb8b7d831310197c7eca8b67d2e42f just pushed to dev.
