### ISSUE TITLE
Error Handler

### ISSUE THREAD

**Issue by licy183** [martinbenes1996/jpeglib#3]
Thanks for such a great job. But when I use this library, I find something strange.

```
import jpeglib
jpeglib.read_dct("xxx.bmp")
```

Codes above will make `python` exit. This is not intended I suppose.

Seems that the wrapper of `libjpeg` doesn't oveeride the default exit handler, which will `exit(EXIT_FAILURE)` by default.

https://github.com/martinbenes1996/jpeglib/blob/f254fa80e37318482d17c0c4ea7d1032c46ab9ac/jpeglib/cjpeglib/cjpeglib.c#L86-L89

https://github.com/martinbenes1996/jpeglib/blob/f254fa80e37318482d17c0c4ea7d1032c46ab9ac/jpeglib/cjpeglib/6b/jerror.c#L69-L79

But when I try to use `setjmp/longjmp` to handle the error, it causes `Segmentation Fault` on Linux. Any ideas?

```c
#include <setjmp.h>

static jmp_buf __error_exit_jmp_buf;

METHODDEF(void)
my_custom_error_exit (j_common_ptr cinfo) {
  /* Write the message */
  (*cinfo->err->output_message) (cinfo);

  /* Let the memory manager delete any temp files before we die */
  jpeg_destroy(cinfo);

  /* Return control to the setjmp point */
  longjmp(__error_exit_jmp_buf, 1);
}

...

  //load image
  cinfo->err = jpeg_std_error(jerr);
  cinfo->err->error_exit = my_custom_error_exit;

  if (setjmp(__error_exit_jmp_buf)) {
    return NULL;
  }

  jpeg_create_decompress(cinfo);
  jpeg_stdio_src(cinfo, fp);
```

**Comment by licy183** [comment]
I have just implent it using C++. But is it possible to handle this error using pure C language?

https://github.com/licy183/jpeglib/commit/f54c70e7948248be9a2033a7cf4a1d1054e0a7a7

**Comment by martinbenes1996** [comment]
Thank you for your input and contribution!

Error handling was one of the things to be done for the production release, and your solution works fine for me. I created a feature branch from this issue.

I'll make some changes there, such as removing the hack with renaming macros into a structure, that is more comprehensible.

**Comment by martinbenes1996** [comment]
Thank you, added to release 0.11.4....
